#!/bin/sh
#PBS -N lammps-water
#PBS -l select=2:ncpus=24:mpiprocs=24:ompthreads=1:mem=96gb
#PBS -l walltime=1:30:00
#PBS -j oe
#PBS -q normal

inputfile="in.water_vitrify"
logfile="log.water_vitrify"

# load module environment
module load lammps/11Aug17/cpu

# change directory to the one where the job was submitted
cd ${PBS_O_WORKDIR}

# run the executable
mpirun "$LAMMPS_EXECUTABLE" -in "$inputfile" -log "$logfile"
